import type { Metadata } from "next";
import Script from "next/script";

import { siteConfig } from "~/config/site";
import { LockTodoAlternativeContent } from "~/components/locktodo-alternative-content";

const NOTION_INTEGRATION_URL = "https://www.notion.com/integrations/lockscreen-todo";
const LOCKTODO_SITE_URL = "https://locktodo.com/";
const PAGE_PATH = "/locktodo-alternative";

const copy = {
  en: {
    seoTitle: "LockTodo vs LockscreenTodo: Which Lock Screen To-Do App Fits Your Workflow?",
    seoDescription:
      "An honest comparison of LockTodo and LockscreenTodo. Both put your tasks on your phone lock screen as a wallpaper. LockTodo reads Apple Reminders and runs offline via Shortcuts; LockscreenTodo pulls Notion tasks onto a custom wallpaper on any phone. See the side-by-side table and FAQ.",
    breadcrumbHome: "Home",
    breadcrumbCurrent: "LockTodo Alternative",
    tldrLabel: "Quick Answer",
    tldrStatement:
      "Both apps turn your to-do list into a lock screen wallpaper. If your tasks live in Apple Reminders and you want a fully offline, no-account setup, LockTodo is a clean choice. If your tasks live in Notion — or you use Android, or you don't want to install an app — LockscreenTodo is the alternative built for you.",
    sectionWhat: "What LockTodo is",
    sectionWhatBody:
      "LockTodo is a minimal iPhone app that turns Apple Reminders into a lock screen wallpaper. It works with the Shortcuts app to refresh your wallpaper automatically, requires iOS 17 or later, needs no account, and processes everything on-device with no tracking. Setup is a one-time flow that takes about five minutes.",
    sectionWhatLink: "Visit locktodo.com",
    sectionWhat2: "What LockscreenTodo is",
    sectionWhat2Body:
      "LockscreenTodo is a lock screen wallpaper generator for Notion users. You connect Notion with read-only OAuth, pick today's tasks, customize the design — templates, gradients, Unsplash photos, or your own image — and save the result as your lock screen. It runs in the browser with no app install required, works for both iPhone and Android, and is listed in Notion's official integration gallery.",
    sectionCompare: "Side-by-side: LockTodo vs LockscreenTodo",
    compareHeaders: ["Dimension", "LockTodo", "LockscreenTodo"],
    compareRows: [
      ["Task source", "Apple Reminders only", "Notion databases, plus manual entry"],
      ["Platform", "iOS 17+ only", "Web — works for iPhone and Android — plus an optional iOS app"],
      ["App install", "Required", "Not required; generate in the browser"],
      ["Account", "None", "Notion OAuth only; no separate account"],
      ["Automation", "Apple Shortcuts: time, location, or Focus based", "Manual refresh — iOS and Android restrict websites from changing the lock screen automatically"],
      ["Data storage", "Fully on-device; no cloud processing", "Read-only OAuth; tasks are never stored on our servers"],
      ["Wallpaper design", "Generated by the app", "Templates, gradients, Unsplash photos, or your own background image"],
      ["Languages", "English", "English and Chinese"],
      ["Price", "Free, no subscription", "Free tier, with an optional Pro plan"],
    ],
    sectionWhenLockTodo: "When LockTodo is the right choice",
    whenLockTodoItems: [
      "Your tasks already live in Apple Reminders and you don't want to migrate anything.",
      "You want a fully offline, no-account, no-tracking setup that stays on your device.",
      "You want automatic wallpaper refreshes via Shortcuts — for example on a schedule, at a location, or per Focus mode.",
      "You only use an iPhone running iOS 17 or later.",
    ],
    sectionWhenLST: "When LockscreenTodo is the right choice",
    whenLSTItems: [
      "Your tasks and plans live in Notion, not Apple Reminders.",
      "You use Android, or switch between iPhone and Android.",
      "You want a designed wallpaper — custom backgrounds, fonts, and layouts — not just text on screen.",
      "You prefer not to install an app, or you want a Chinese-language interface.",
    ],
    sectionNotion: "The Notion angle: why the two apps barely overlap",
    sectionNotionBody:
      "LockTodo reads Apple Reminders; LockscreenTodo reads Notion. If your second brain, projects, and to-do lists live in Notion, a Reminders-based app simply cannot see them. LockscreenTodo is listed in Notion's official integration gallery and connects with read-only OAuth, so your workspace stays the source of truth while your lock screen shows the few tasks that matter today.",
    notionButton: "See the Notion integration listing",
    sectionBoth: "Can you use both?",
    sectionBothBody:
      "Yes — they don't conflict. Some people keep Apple Reminders for quick personal errands with LockTodo, and use LockscreenTodo for the Notion projects they actually plan their day around. Each app renders its own wallpaper; you simply pick which one is on your lock screen at any given time.",
    faqTitle: "Frequently asked questions",
    faqs: [
      {
        q: "Is LockscreenTodo a good LockTodo alternative?",
        a: "It depends on where your tasks live. If you plan in Notion, LockscreenTodo is the direct alternative — it is the only lock screen wallpaper tool in Notion's official integration gallery. If you live inside Apple Reminders and want fully offline automation, LockTodo is built exactly for that.",
      },
      {
        q: "Which one works on Android?",
        a: "LockscreenTodo. The wallpaper it generates is a standard image that any Android phone can set as a lock screen. LockTodo is an iOS-only app and requires iOS 17 or later.",
      },
      {
        q: "Which one is more private?",
        a: "Both take privacy seriously, with different models. LockTodo processes everything on-device with no account and no tracking. LockscreenTodo uses read-only Notion OAuth — it can see the tasks you share but cannot modify your workspace, and it never stores your tasks on its servers.",
      },
      {
        q: "Does LockscreenTodo update the lock screen automatically like LockTodo does with Shortcuts?",
        a: "Not in the current web version. iOS and Android restrict websites from changing the lock screen on your behalf, so you regenerate and re-save the wallpaper when priorities change — the flow takes about a minute. Automatic rotation via Shortcuts and Live Activities is on the roadmap.",
      },
      {
        q: "Do I need Apple Reminders to use LockscreenTodo?",
        a: "No. LockscreenTodo connects to Notion, or you can type tasks manually without connecting anything. Apple Reminders is not involved at all.",
      },
      {
        q: "Is LockscreenTodo free?",
        a: "Yes, there is a free tier that covers generating and downloading your lock screen wallpaper. An optional Pro plan unlocks premium features. LockTodo is also free with no subscription, according to its site.",
      },
    ],
    ctaEyebrow: "Try the Notion side",
    ctaTitle: "Put your Notion tasks where you can't miss them.",
    ctaBody:
      "Generate a lock screen wallpaper from your Notion to-do list in under a minute. Free preview, no app install required.",
    ctaPrimary: "Generate my wallpaper",
    ctaSecondary: "See all use cases",
  },
  zh: {
    seoTitle: "LockTodo vs LockscreenTodo：哪款锁屏待办工具适合你的工作流？",
    seoDescription:
      "LockTodo 和 LockscreenTodo 的诚实对比。两者都把待办事项变成手机锁屏壁纸：LockTodo 读取 Apple 提醒事项、通过快捷指令离线运行；LockscreenTodo 把 Notion 任务生成自定义锁屏壁纸，任何手机都能用。附对比表和常见问题。",
    breadcrumbHome: "首页",
    breadcrumbCurrent: "对比 LockTodo",
    tldrLabel: "一句话结论",
    tldrStatement:
      "两款产品都是把待办清单变成锁屏壁纸。如果你的任务在 Apple 提醒事项里、想要完全离线无账号的方案，LockTodo 是干净的选择。如果你的任务在 Notion 里——或者你用 Android、不想装 App——LockscreenTodo 才是为你做的那个替代品。",
    sectionWhat: "LockTodo 是什么",
    sectionWhatBody:
      "LockTodo 是一款极简 iPhone 应用，把 Apple 提醒事项变成锁屏壁纸。它配合快捷指令自动刷新壁纸，要求 iOS 17 及以上，不需要账号，所有处理都在设备本地完成、无追踪。设置是一次性的，大约五分钟。",
    sectionWhatLink: "访问 locktodo.com",
    sectionWhat2: "LockscreenTodo 是什么",
    sectionWhat2Body:
      "LockscreenTodo 是为 Notion 用户做的锁屏壁纸生成器。用只读 OAuth 连接 Notion，挑选今天的任务，自定义设计——模板、渐变、Unsplash 图库或自己的照片——然后保存为锁屏。它在浏览器里运行，不需要安装 App，iPhone 和 Android 都能用，并且被收录在 Notion 官方集成目录里。",
    sectionCompare: "正面对比：LockTodo vs LockscreenTodo",
    compareHeaders: ["维度", "LockTodo", "LockscreenTodo"],
    compareRows: [
      ["任务来源", "仅 Apple 提醒事项", "Notion 数据库，也支持手动输入"],
      ["平台", "仅 iOS 17+", "网页版（iPhone 和 Android 通用），另有可选 iOS App"],
      ["需要装 App", "必须安装", "不需要，浏览器里直接生成"],
      ["账号", "无", "仅 Notion OAuth，没有独立账号体系"],
      ["自动化", "快捷指令：按时间、地点或专注模式刷新", "手动刷新——iOS 和 Android 都限制网页自动修改锁屏"],
      ["数据存储", "完全在设备本地，无云端处理", "只读 OAuth，任务绝不存储在我们的服务器上"],
      ["壁纸设计", "由 App 生成", "模板、渐变、Unsplash 图库或自定义背景图"],
      ["语言", "英文", "中文和英文"],
      ["价格", "免费，无订阅", "免费版够用，另有可选 Pro 方案"],
    ],
    sectionWhenLockTodo: "什么时候选 LockTodo",
    whenLockTodoItems: [
      "你的任务本来就在 Apple 提醒事项里，不想迁移任何东西。",
      "你想要完全离线、无账号、无追踪、一切留在本机的方案。",
      "你想通过快捷指令自动刷新壁纸——比如定时、到某个地点、或跟随专注模式。",
      "你只用运行 iOS 17 及以上的 iPhone。",
    ],
    sectionWhenLST: "什么时候选 LockscreenTodo",
    whenLSTItems: [
      "你的任务和计划都在 Notion 里，而不是 Apple 提醒事项。",
      "你用 Android，或者在 iPhone 和 Android 之间切换。",
      "你想要有设计感的壁纸——自定义背景、字体和排版——而不只是屏幕上的文字。",
      "你不想安装 App，或者需要中文界面。",
    ],
    sectionNotion: "Notion 视角：为什么两款产品几乎不重叠",
    sectionNotionBody:
      "LockTodo 读的是 Apple 提醒事项，LockscreenTodo 读的是 Notion。如果你的第二大脑、项目和待办清单都在 Notion 里，基于提醒事项的应用根本看不到它们。LockscreenTodo 被收录在 Notion 官方集成目录中，用只读 OAuth 连接——Notion 始终是数据源头，锁屏只展示今天最重要的几件事。",
    notionButton: "查看 Notion 官方集成页",
    sectionBoth: "两个能一起用吗？",
    sectionBothBody:
      "可以——它们互不冲突。有人用 LockTodo 管 Apple 提醒事项里的生活杂事，用 LockscreenTodo 管真正围绕其安排一天的 Notion 项目。两个应用各自生成自己的壁纸，你在任意时刻选择哪一张放在锁屏上即可。",
    faqTitle: "常见问题",
    faqs: [
      {
        q: "LockscreenTodo 是 LockTodo 的好替代品吗？",
        a: "取决于你的任务在哪里。如果你用 Notion 做计划，LockscreenTodo 就是直接替代品——它是 Notion 官方集成目录里唯一的锁屏壁纸工具。如果你深度使用 Apple 提醒事项、想要完全离线的自动化，LockTodo 正是为此而生。",
      },
      {
        q: "哪个支持 Android？",
        a: "LockscreenTodo。它生成的壁纸是普通图片，任何 Android 手机都能设为锁屏。LockTodo 是 iOS 独占应用，且要求 iOS 17 及以上。",
      },
      {
        q: "哪个更保护隐私？",
        a: "两者都重视隐私，只是模式不同。LockTodo 一切在设备本地处理，无账号、无追踪。LockscreenTodo 使用 Notion 只读 OAuth——只能读取你分享的任务，无法修改你的工作区，也绝不会把任务存储在我们的服务器上。",
      },
      {
        q: "LockscreenTodo 能像 LockTodo 那样用快捷指令自动更新锁屏吗？",
        a: "当前网页版不能。iOS 和 Android 都限制网站替用户修改锁屏，所以优先级变化时需要重新生成并保存壁纸——整个流程约一分钟。通过快捷指令和 Live Activities 自动轮换已在路线图上。",
      },
      {
        q: "用 LockscreenTodo 需要 Apple 提醒事项吗？",
        a: "不需要。LockscreenTodo 连接的是 Notion，或者不连接任何账号直接手动输入任务。Apple 提醒事项完全不参与。",
      },
      {
        q: "LockscreenTodo 免费吗？",
        a: "是的，免费版即可生成并下载锁屏壁纸，另有可选的 Pro 方案解锁高级功能。根据其官网，LockTodo 也是免费的、无订阅。",
      },
    ],
    ctaEyebrow: "试试 Notion 这边",
    ctaTitle: "把你的 Notion 任务放到无法忽视的地方。",
    ctaBody: "一分钟内把你的 Notion 待办清单生成锁屏壁纸。免费预览，无需安装 App。",
    ctaPrimary: "立即生成我的壁纸",
    ctaSecondary: "查看全部场景",
  },
} as const;

type Locale = "en" | "zh";

function pickLocale(value: string | undefined): Locale {
  return value === "zh" ? "zh" : "en";
}

type PageProps = {
  params: { lang: string };
};

export function generateStaticParams() {
  return [{ lang: "en" }, { lang: "zh" }];
}

export function generateMetadata({ params }: PageProps): Metadata {
  const lang = pickLocale(params.lang);
  const t = copy[lang];
  const canonical = `${siteConfig.url}${lang === "zh" ? "/zh" : "/en"}${PAGE_PATH}`;

  return {
    title: t.seoTitle,
    description: t.seoDescription,
    alternates: {
      canonical,
      languages: {
        en: `${siteConfig.url}/en${PAGE_PATH}`,
        zh: `${siteConfig.url}/zh${PAGE_PATH}`,
      },
    },
    openGraph: {
      title: t.seoTitle,
      description: t.seoDescription,
      url: canonical,
      type: "article",
    },
  };
}

const jsonLdForLocale = (locale: Locale) => {
  const t = copy[locale];
  const pageUrl = `${siteConfig.url}${locale === "zh" ? "/zh" : "/en"}${PAGE_PATH}`;
  const inLanguage = locale === "zh" ? "zh-Hans" : "en-US";

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: t.seoTitle,
    description: t.seoDescription,
    inLanguage,
    datePublished: "2026-08-10",
    dateModified: "2026-08-10",
    author: {
      "@type": "Organization",
      name: "Lockscreen Todo",
      url: siteConfig.url,
    },
    publisher: {
      "@type": "Organization",
      name: "Lockscreen Todo",
      url: siteConfig.url,
      logo: {
        "@type": "ImageObject",
        url: `${siteConfig.url}/og-image.jpg`,
      },
    },
    mainEntityOfPage: pageUrl,
    sameAs: [NOTION_INTEGRATION_URL],
    about: [
      { "@type": "Thing", name: "LockTodo" },
      { "@type": "Thing", name: "LockscreenTodo" },
      { "@type": "Thing", name: locale === "zh" ? "锁屏待办" : "Lock screen to-do list" },
    ],
  };

  const softwareSchema = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Lockscreen Todo",
    applicationCategory: "ProductivityApplication",
    operatingSystem: "iOS, Android, Web",
    description: t.seoDescription,
    url: siteConfig.url,
    inLanguage,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
    sameAs: [NOTION_INTEGRATION_URL, "https://www.producthunt.com/products/lockscreen-todo"],
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    inLanguage,
    mainEntity: t.faqs.map((item) => ({
      "@type": "Question",
      name: item.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.a,
      },
    })),
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: t.breadcrumbHome,
        item: `${siteConfig.url}${locale === "zh" ? "/zh" : "/en"}`,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: t.breadcrumbCurrent,
        item: pageUrl,
      },
    ],
  };

  return [articleSchema, softwareSchema, faqSchema, breadcrumbSchema];
};

export default function LockTodoAlternativePage({ params }: PageProps) {
  const lang = pickLocale(params.lang);
  const t = copy[lang];
  const schemas = jsonLdForLocale(lang);

  return (
    <>
      {schemas.map((schema, index) => (
        <Script
          key={index}
          id={`ld-${lang}-${index}`}
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
        />
      ))}
      <LockTodoAlternativeContent
        lang={lang}
        copy={t}
        notionIntegrationUrl={NOTION_INTEGRATION_URL}
        locktodoSiteUrl={LOCKTODO_SITE_URL}
      />
    </>
  );
}
